Refactor/remove experimental decorators attribute validate
iunu/mobx-async-store pull request #414
Opened 2022-11-28 22:24 UTC by dsalazar357

### Description
Removes experimental decorators for `@attributes` and `@validate`
### Changes
- Refactor default attributes definition
- Removes references to `schema structure` in model an store
- Fixes tests to match new default attributes

2022-11-29 22:34 UTC, dudeofawesome commented on src/utils.js
> +}
I think it makes more sense to just do the type checking inline.

2022-11-29 22:38 UTC, dudeofawesome commented on spec/Model.spec.js
> +      message: 'can\'t be blank'
Prefer to use `"` or \` when making a string with a `'`

2022-11-29 22:38 UTC, dudeofawesome approved these changes

2022-11-30 04:42 UTC, jondayton commented on spec/Model.spec.js
> +  }
why is this a getter instead of an attribute?

2022-11-30 04:53 UTC, jondayton commented on src/Model.js
> +          if (attributeDefinitions[key].transformer) { attr = attributeDefinitions[key].transformer(value) }
should the transformer be first now? previously 'Date', 'Array' were acting as a type of transformer

2022-12-02 18:07 UTC, jondayton requested changes

2022-12-02 18:07 UTC, jondayton commented on src/Model.js
> +  } */
delete this code

2022-12-02 18:07 UTC, jondayton commented on src/Store.js
> +    const attributeNames = Object.keys(properties)
This is meant to make sure you're only picking properties that are defined as attributes, not other properties on the object.

2022-12-02 18:42 UTC, jondayton approved these changes
Looks good! bump to version `5.0.0-rc1`

2022-12-02 20:52 UTC, merged